:sparkles: Installer: Add installer project.
dd-center/obs-streamlink pull request #1
Opened 2020-01-25 10:45 UTC by Afanyiyu

2020-01-25 11:24 UTC, cqjjjzr requested changes
未包含判断安装路径有效性的脚本？

2020-01-26 07:33 UTC, Afanyiyu commented
> 未包含判断安装路径有效性的脚本？

>经验证，脚本貌似不能返回有效的信息。

这一观点正在重新被验证，更改正在进行中。

2020-02-02 14:36 UTC, Afanyiyu commented
> 未包含判断安装路径有效性的脚本？

在
https://github.com/dd-center/obs-streamlink/pull/1/commits/72c9e671b3f39838bb0965f9be1ef8a7ce01e6aa
中已经对这一问题进行了修复。

请前往
https://github.com/dd-center/obs-streamlink/blob/ilharper/installer/installer/dialogs.ail
和
https://github.com/dd-center/obs-streamlink/blob/ilharper/installer/installer/dictionary.ail
检查翻译。

2020-02-02 14:42 UTC, cqjjjzr approved these changes
approved

2020-02-02 14:43 UTC, merged